apiVersion: v1
kind: Secret
metadata:
  name: private-argocd-repo
  namespace: argocd
  labels:
        app: myapp
stringData:
  url: https://github.com/John-Roger-Org/argocd-lab.git
  password: ${GITHUB_TOKEN}
  username: not-used
